Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/tornado-3.2-py2.7-macosx-10.8-intel.egg/tornado/web.py", line 1218, in _when_complete
    callback()
  File "/Library/Python/2.7/site-packages/tornado-3.2-py2.7-macosx-10.8-intel.egg/tornado/web.py", line 1239, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "/Library/Python/2.7/site-packages/tornado-3.2-py2.7-macosx-10.8-intel.egg/tornado/web.py", line 1897, in get
    self.root, absolute_path)
  File "/Library/Python/2.7/site-packages/tornado-3.2-py2.7-macosx-10.8-intel.egg/tornado/web.py", line 2065, in validate_absolute_path
    raise HTTPError(404)
HTTPError: HTTP 404: Not Found
